[package]
name = "stratax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
tokio = { version = "1", features = ["full"] }
xcb = "1.2.1"
xcb-util = "0.4.0"
